WidgetsExample:

<WidgetsExample>:
    cols: 3
    Button: 
        text: "Click here"
        on_press: root.on_button_click()
    Label: 
        text: root.my_text 
        font_name: "Fonts/Poppins-Bold.ttf" # 1
        font_size: "20dp" # 2
        color: 1, 0.5, 1, 1 # 3




# 1
# Once you've downloaded the font that you want to use, you use "font_name" to change the 
# font. 

# 2
# You use "font_size" to adjust the font size

# 3 
# You use "color" to change the font color